### ISSUE TITLE
Cannot read property 'rules' of undefined

### ISSUE THREAD

**Issue by boomshroom** [Leochan6/leochan6.github.io#1]
This appears to occur in both Brave and Chome, implying that it might be a chromium specific error. As it stands this prevents me from adding any characters to a given list. This was found while testing the site anonymously, so it might not have happened if I were logged in (and I'm naturally nervous about creating an entirely new login and password for such a small project).

```
@firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'rules' of undefined
    at Module.setProfile (https://leo-chan.me/magireco/character/js/profile_api.js:89:39)
    at selectList (https://leo-chan.me/magireco/character/js/character_list_api.js:100:15)
    at Module.setLists (https://leo-chan.me/magireco/character/js/character_list_api.js:49:7)
    at loadLists (https://leo-chan.me/magireco/character/js/storage_api.js:126:22)
    at https://leo-chan.me/magireco/shared/js/database_api.js:156:5
    at https://www.gstatic.com/firebasejs/7.12.0/firebase-database.js:1:56884
    at It (https://www.gstatic.com/firebasejs/7.12.0/firebase-database.js:1:18280)
    at Fr.raise (https://www.gstatic.com/firebasejs/7.12.0/firebase-database.js:1:112377)
    at xr.raiseQueuedEventsMatchingPredicate_ (https://www.gstatic.com/firebasejs/7.12.0/firebase-database.js:1:111987)
    at xr.raiseEventsForChangedPath (https://www.gstatic.com/firebasejs/7.12.0/firebase-database.js:1:111702)
```

**Comment by Leochan6** [comment]
@boomshroom Could you tell me what you named your list as?

**Comment by boomshroom** [comment]
At first I just named it today's date: `2020-05-13`, I also tried with `test` and it still didn't work.

**Comment by Leochan6** [comment]
Actually, this error had to do with an update I made to the ordering of rules. It should be fixed now.
